[build]
target = "index.html" # The index HTML file to drive the bundling process.
release = true # Build in release mode.
dist = "trunk-output" # The output dir for all final assets.
public_url = "/" # The public URL from which assets are to be served.


[watch]
# Paths to watch. The `build.target`'s parent folder is watched by default.
watch = []
# Paths to ignore.
ignore = []

[serve]
addr = "127.0.0.1" # The address to serve on.
port = 8080 # The port to serve on.
open = true # Open a browser tab once the initial build is complete.
no_autoreload = false # Disable auto-reload of the web app.

[clean]
dist = "trunk-output" # The output dir for all final assets.
cargo = false # Optionally perform a cargo clean.

